version: 2.1

orbs:
  tf: nutrien/tf@dev:alpha

prod-context: &prod-context
  context: production

dev-context: &dev-context
  context: development

workflows:
  terraform:
    description: A workflow that runs the plan and apply job in each environment
    jobs:
      - tf/plan:
          <<: *dev-context
          name: dev_plan
          env: dev
          filters:
            branches:
              ignore:
                - master
                - develop
      - tf/plan:
          <<: *prod-context
          name: prod_plan
          env: prod
          filters:
            branches:
              only:
                - develop
      - tf/apply:
          <<: *dev-context
          name: dev_apply
          env: dev
          filters:
            branches:
              only:
                - develop
      - tf/apply:
          <<: *prod-context
          name: prod_apply
          env: prod
          filters:
            branches:
              only:
                - master
  drift_detection:
    description: A scheduled workflow to run daily at 2pm UTC to detect drift in the prod environment. Job will fail if state does not match the real environment.
    triggers:
      - schedule:
          cron: "0 14 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - tf/detectdrift:
          <<: *prod-context
          name: drift_detect
          env: prod

